#!/bin/bash

# export environment variables
export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:$PWD/build
export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:$PWD/models
export GAZEBO_RESOURCE_PATH=${GAZEBO_RESOURCE_PATH}:$PWD

# run each process in its own shell
terminator -e "roscore" &
terminator -e "python ./OpenCV/follower_opencv0.py" &
terminator -e "python ./OpenCV/follower_opencv1.py" &
terminator -e "rosrun gazebo_ros gazebo -s libgazebo_ros_api_plugin.so models/trafficCircle.world -u --verbose" &
