#!/bin/bash
export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:$PWD/build
xterm -e roscore &
xterm -e python ./OpenCV/follower_opencv.py &
xterm -e rosrun gazebo_ros gazebo gazonoVehicle.world -u --verbose
