#!/bin/bash
export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:$PWD/build
terminator -e "roscore" &
terminator -e "python ./OpenCV/follower_opencv.py" &
terminator -e "python ./OpenCV/laser_viewer.py" &
terminator -e "rosrun gazebo_ros gazebo -s libgazebo_ros_api_plugin.so ./gazonoVehicle.world -u --verbose"
